In [2]:
import pandas as pd
import numpy as np
import re
from sqlalchemy import create_engine , inspect

In [14]:
user = "postgres"
password = "mnbvcxz1234567"
host = "3.111.61.248" # "3.109.41.47"
port = 5432
database = "de_db"
 
conn = f"postgresql://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(conn)

In [15]:
engine

Engine(postgresql://postgres:***@3.111.61.248:5432/de_db)

In [16]:
inspector = inspect(engine)
table_names = inspector.get_table_names()

In [17]:
table_names

['spatial_ref_sys',
 'indicatr',
 'city_poi',
 'city',
 'brand_nm_104_competitors',
 'district',
 'district_poi',
 'state',
 'property_data_cs',
 'city_cs_avgcount',
 'village',
 'd_date',
 'village_poi',
 'hexgrid08_poi',
 'hexgrid08_footfall',
 'locality',
 'property_data',
 'hexgrid08_cs',
 'locality_cs',
 'city_data',
 'property_footfall',
 'locality_bom',
 'locality_geo_cod',
 'poi',
 'locality_data',
 'brand_com',
 'property',
 'hexgrid08',
 'hexgrid08_data']

In [3]:
df = pd.DataFrame()  # Initialize an empty DataFrame to hold the final result
indicator = ['building_density',"average_monthly_residential_rental_price"]

for i in indicator:
    query = f"SELECT hexid08, t_name, is_tc, val AS {i} FROM public.hexgrid08_data WHERE indicatr = '{i}' AND t_name = 'Amritsar'"
    result = engine.execute(query)
    rows = result.fetchall()
    
    if len(rows) > 0:  # If there are results for this indicator
        column_names = result.keys()
        temp_df = pd.DataFrame(rows, columns=column_names)
        
        # Dropping duplicate columns if they exist in the new DataFrame
        columns_to_drop = [col for col in temp_df.columns if col in df.columns]
        temp_df = temp_df.drop(columns=columns_to_drop, errors='ignore')
        
        # Concatenating the new DataFrame to the existing master DataFrame
        df = pd.concat([df, temp_df], axis=1)

# Now df contains the merged DataFrame without duplicate columns

NameError: name 'engine' is not defined

In [28]:
df.to_csv(r'D:\Sociometrik\rent prediction\raw files\amritsar_raw\amritsar_building density.csv')

In [10]:
buffer_data=pd.read_csv(r"C:\Users\chemi\Downloads\starbucks_h8_mapped.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Sociometrik\\rent prediction\\raw files\\amritsar_raw\\amritsar_building_density.csv'

In [28]:
buffer_data=buffer_data.merge(df,how="left", on=["hexid08",'t_name','is_tc'])

In [39]:
buffer_data=buffer_data.drop(columns=["lat",'lon','hexid08','is_tc','t_name'])

In [90]:
buffer_data.to_csv(r"C:\Users\chemi\Desktop\enviroments\myml\1-Notebooks_python\All Scripts\extract datafrom the data base\output_csv\starbucks\all_data_on_grid_level.csv")

In [97]:
df=pd.read_csv(r"C:\Users\chemi\Desktop\enviroments\myml\1-Notebooks_python\All Scripts\extract datafrom the data base\output_csv\starbucks\all_data_on_grid_level.csv")

In [98]:
df=df.groupby(['name',"buff_id"]).agg({'average_monthly_residential_rental_price': 'mean','building_density': 'mean',
    'green_space_density': 'mean',
    'road_length': 'sum',
    'transportation_hubs': 'sum',
    'daily_avg_footfall': 'mean',
    'weekly_avg_footfall': 'mean',
    'consumer_digital_expenditure': 'sum',
    'total_digital_consumers': 'sum',
    'elderly_population': 'sum',
    'female_population': 'sum',
    'female_population_15_to_49years': 'sum',
    'kids_population': 'sum',
    'male_population': 'sum',
    'population': 'sum',
    'population_density': 'mean',
    'youth_population': 'sum',
    'average_monthly_commercial_rental_price': 'mean',
    'auto_dealership': 'sum',
    'auto_service_maintenance': 'sum',
    'motorcycle_dealership': 'sum',
    'truck_dealership': 'sum',
    'business_facility': 'sum',
    'government_office': 'sum',
    'post_office': 'sum',
    'book_store': 'sum',
    'higher_education': 'sum',
    'library': 'sum',
    'school': 'sum',
    'training_centre_institute': 'sum',
    'amusement_park': 'sum',
    'bowling_centre': 'sum',
    'casino': 'sum',
    'cinema': 'sum',
    'golf_course': 'sum',
    'golf_practice_range': 'sum',
    'ice_skating_rink': 'sum',
    'museum': 'sum',
    'nightlife': 'sum',
    'park_recreation_area': 'sum',
    'performing_arts': 'sum',
    'sports_centre': 'sum',
    'atm': 'sum',
    'bank': 'sum',
    'hospital': 'sum',
    'medical_service': 'sum',
    'pharmacy': 'sum',
    'industrial_zone': 'sum',
    'police_station': 'sum',
    'bar_or_pub': 'sum',
    'coffee_shop': 'sum',
    'restaurant': 'sum',
    'clothing_store': 'sum',
    'consumer_electronics_store': 'sum',
    'convenience_store': 'sum',
    'department_store': 'sum',
    'grocery_store': 'sum',
    'home_improvement_hardware_store': 'sum',
    'home_specialty_store': 'sum',
    'office_supply_services_store': 'sum',
    'petrol_gasoline_station': 'sum',
    'shopping': 'sum',
    'sporting_goods_store': 'sum',
    'airport': 'sum',
    'bus_station': 'sum',
    'train_station': 'sum',
    'transportation_service': 'sum',
    'hotel': 'sum',
    'premium_hotels': 'sum',
    'jewellery_store': 'sum',
    })

In [99]:
df=df.reset_index().sort_values("buff_id")

In [100]:
df

,name,buff_id,average_monthly_residential_rental_price,building_density,green_space_density,road_length,transportation_hubs,daily_avg_footfall,weekly_avg_footfall,consumer_digital_expenditure,...,petrol_gasoline_station,shopping,sporting_goods_store,airport,bus_station,train_station,transportation_service,hotel,premium_hotels,jewellery_store
35,starbucks coffee house,buff0001,23.988889,502.946667,0.122222,138065.11,4,66.666667,206.000000,5970577,...,1,11,1,0,2,0,0,8,0,0
12,starbucks - church street (s036),buff0002,38.956000,242.320000,0.114000,95841.39,37,80.100000,366.700000,3184294,...,3,0,11,0,0,0,51,3,0,0
0,indiranagar starbucks,buff0003,31.272500,998.853333,0.105556,121494.13,9,56.444444,335.000000,6284349,...,0,3,0,0,4,0,31,10,0,0
19,starbucks coffee,buff0004,34.905000,539.191111,0.127778,103116.17,13,20.777778,366.111111,5141982,...,3,0,3,0,0,0,36,14,0,0
20,starbucks coffee,buff0005,67.438000,206.422222,0.040000,101080.58,28,44.222222,177.111111,2290906,...,8,0,0,0,1,0,26,9,0,1
39,starbucks vittal mallya road,buff0006,38.028889,193.709000,0.126000,109976.58,32,59.800000,324.600000,3358805,...,4,0,4,0,1,0,19,4,0,0
21,starbucks coffee,buff0007,28.028889,332.557778,0.055556,110860.56,6,18.777778,146.666667,6094620,...,0,1,0,0,1,0,23,22,0,0
1,starbucks,buff0008,28.630000,530.815000,0.074000,123993.72,22,55.300000,235.700000,5408223,...,6,0,0,0,4,0,0,9,0,0
22,starbucks coffee,buff0009,31.222857,375.753333,0.063333,138112.06,16,71.888889,233.111111,1545169,...,1,2,1,0,0,0,3,23,0,0
23,starbucks coffee,buff0010,26.467500,836.086250,0.055000,101149.75,0,45.875000,428.500000,2705967,...,0,1,3,0,0,0,29,6,0,0
2,starbucks,buff0011,82.813333,1265.235556,0.080000,120093.59,44,45.666667,508.444444,2595368,...,1,0,0,0,3,0,9,7,0,0
3,starbucks,buff0012,26.663000,429.655000,0.112000,155711.81,14,42.600000,246.800000,3821628,...,1,11,1,0,8,0,31,9,0,0
24,starbucks coffee,buff0013,23.711111,425.360909,0.100000,105621.98,53,73.000000,298.363636,5753766,...,3,4,3,0,3,0,5,3,0,0
41,tata starbucks coffee,buff0014,25.010000,421.324000,0.082000,126704.36,3,39.400000,547.500000,4406629,...,1,0,5,0,2,0,20,5,0,1
25,starbucks coffee,buff0015,25.501250,558.675556,0.050000,117498.24,36,54.666667,286.888889,6438157,...,4,0,2,0,1,0,2,7,0,0
26,starbucks coffee,buff0016,29.795000,174.201111,0.144444,86316.08,35,84.888889,468.666667,2904514,...,1,0,7,0,0,0,39,3,0,0
27,starbucks coffee,buff0017,17.377778,376.552222,0.078889,93867.65,27,62.777778,322.555556,1748227,...,1,2,8,0,2,0,24,14,0,0
4,starbucks,buff0018,21.345000,207.323333,0.100000,108705.76,3,45.666667,285.222222,2686794,...,3,0,10,0,1,0,12,9,0,0
5,starbucks,buff0019,33.738333,353.212500,0.056250,117912.57,16,34.625000,227.500000,1284589,...,1,2,1,0,0,0,3,21,0,0
17,starbucks at samsung opera house,buff0020,40.529000,476.000000,0.131000,107649.99,33,25.000000,451.300000,3405417,...,2,0,6,0,0,0,35,4,0,0
28,starbucks coffee,buff0021,41.828750,501.535000,0.153750,93064.63,7,21.625000,403.125000,3275703,...,2,0,6,0,0,0,31,4,0,0
34,"starbucks coffee cunningham, india",buff0022,28.868571,65.433333,0.116667,142484.72,31,153.111111,382.222222,3459404,...,7,0,3,0,0,0,17,1,0,0
36,starbucks dollars colony,buff0023,23.140000,341.365000,0.133000,118562.69,45,30.500000,287.300000,1302210,...,2,0,2,0,0,0,7,12,0,0
14,starbucks - kalyananagar (s152),buff0024,29.337000,409.418000,0.087000,121135.02,23,54.300000,478.800000,4158149,...,2,0,0,0,2,0,1,21,0,0
29,starbucks coffee,buff0025,28.797143,90.460000,0.136667,153421.40,32,98.777778,351.777778,2641935,...,6,0,0,0,2,0,0,3,0,0
15,starbucks - prestige shantiniketan (s071),buff0026,18.220000,93.307273,0.080909,119547.27,10,64.727273,374.545455,5749688,...,3,3,0,0,2,0,23,31,0,0
30,starbucks coffee,buff0027,31.642500,374.648889,0.135556,113861.19,9,17.777778,278.333333,4949139,...,1,0,6,0,2,0,2,18,0,1
38,starbucks vega city,buff0028,25.365556,94.495556,0.101111,103598.39,4,69.222222,415.222222,5138829,...,1,0,11,0,2,0,9,13,0,0
31,starbucks coffee,buff0029,18.260000,314.836000,0.117000,139689.46,8,75.400000,293.300000,8047903,...,3,0,0,0,1,0,4,5,0,0
6,starbucks,buff0030,41.503333,200.277000,0.059000,133202.63,18,57.100000,394.100000,4556611,...,1,1,0,0,5,0,0,37,0,0
7,starbucks,buff0031,37.416667,66.190000,0.090000,131596.50,19,38.111111,166.333333,4336746,...,1,2,0,0,5,0,8,26,0,0
37,starbucks nexus shantiniketan,buff0032,18.388571,102.638000,0.096000,116802.98,10,70.400000,362.300000,6865900,...,3,3,0,0,5,0,21,28,0,0
8,starbucks,buff0033,27.566667,343.735000,0.114000,134412.72,13,35.300000,227.200000,3690480,...,0,3,2,0,2,0,11,39,0,1
32,starbucks coffee,buff0034,23.932500,149.615833,0.055000,149704.88,37,51.250000,376.833333,8695635,...,2,0,7,0,2,0,12,23,0,0
33,starbucks coffee,buff0035,16.346667,507.391000,0.074000,148657.82,10,78.500000,428.500000,8990008,...,2,5,17,0,1,0,16,3,0,0
16,starbucks - sjr central (s262),buff0036,17.377778,376.552222,0.078889,93867.65,27,62.777778,322.555556,1748227,...,1,2,8,0,2,0,24,14,0,0
40,starbucks vr mall,buff0037,23.105556,383.262727,0.103636,120732.81,53,83.545455,192.636364,3820777,...,1,4,3,0,3,0,5,6,0,0
18,starbucks bhartiya mall of bangalore,buff0038,133.915000,41.651429,0.142857,100314.18,23,33.857143,403.571429,4712787,...,0,1,3,0,4,0,1,11,0,0
9,starbucks,buff0039,50.595000,713.098571,0.142857,99136.35,4,36.428571,312.571429,3163216,...,1,0,1,0,1,0,1,2,0,0
11,starbucks - bhartiya city (s319),buff0040,100.883333,350.026250,0.127500,110886.81,23,31.625000,448.125000,4744863,...,0,1,3,0,4,0,1,11,0,0
10,starbucks,buff0041,40.955714,55.084286,0.141429,90005.11,5,49.714286,376.000000,2413856,...,1,0,3,0,1,0,20,3,0,0
13,starbucks - goldman sachs (s172),buff0042,41.503333,200.277000,0.059000,133202.63,18,57.100000,394.100000,4556611,...,1,1,0,0,5,0,0,37,0,0

In [101]:
df

,name,buff_id,average_monthly_residential_rental_price,building_density,green_space_density,road_length,transportation_hubs,daily_avg_footfall,weekly_avg_footfall,consumer_digital_expenditure,...,petrol_gasoline_station,shopping,sporting_goods_store,airport,bus_station,train_station,transportation_service,hotel,premium_hotels,jewellery_store
35,starbucks coffee house,buff0001,23.988889,502.946667,0.122222,138065.11,4,66.666667,206.000000,5970577,...,1,11,1,0,2,0,0,8,0,0
12,starbucks - church street (s036),buff0002,38.956000,242.320000,0.114000,95841.39,37,80.100000,366.700000,3184294,...,3,0,11,0,0,0,51,3,0,0
0,indiranagar starbucks,buff0003,31.272500,998.853333,0.105556,121494.13,9,56.444444,335.000000,6284349,...,0,3,0,0,4,0,31,10,0,0
19,starbucks coffee,buff0004,34.905000,539.191111,0.127778,103116.17,13,20.777778,366.111111,5141982,...,3,0,3,0,0,0,36,14,0,0
20,starbucks coffee,buff0005,67.438000,206.422222,0.040000,101080.58,28,44.222222,177.111111,2290906,...,8,0,0,0,1,0,26,9,0,1
39,starbucks vittal mallya road,buff0006,38.028889,193.709000,0.126000,109976.58,32,59.800000,324.600000,3358805,...,4,0,4,0,1,0,19,4,0,0
21,starbucks coffee,buff0007,28.028889,332.557778,0.055556,110860.56,6,18.777778,146.666667,6094620,...,0,1,0,0,1,0,23,22,0,0
1,starbucks,buff0008,28.630000,530.815000,0.074000,123993.72,22,55.300000,235.700000,5408223,...,6,0,0,0,4,0,0,9,0,0
22,starbucks coffee,buff0009,31.222857,375.753333,0.063333,138112.06,16,71.888889,233.111111,1545169,...,1,2,1,0,0,0,3,23,0,0
23,starbucks coffee,buff0010,26.467500,836.086250,0.055000,101149.75,0,45.875000,428.500000,2705967,...,0,1,3,0,0,0,29,6,0,0
2,starbucks,buff0011,82.813333,1265.235556,0.080000,120093.59,44,45.666667,508.444444,2595368,...,1,0,0,0,3,0,9,7,0,0
3,starbucks,buff0012,26.663000,429.655000,0.112000,155711.81,14,42.600000,246.800000,3821628,...,1,11,1,0,8,0,31,9,0,0
24,starbucks coffee,buff0013,23.711111,425.360909,0.100000,105621.98,53,73.000000,298.363636,5753766,...,3,4,3,0,3,0,5,3,0,0
41,tata starbucks coffee,buff0014,25.010000,421.324000,0.082000,126704.36,3,39.400000,547.500000,4406629,...,1,0,5,0,2,0,20,5,0,1
25,starbucks coffee,buff0015,25.501250,558.675556,0.050000,117498.24,36,54.666667,286.888889,6438157,...,4,0,2,0,1,0,2,7,0,0
26,starbucks coffee,buff0016,29.795000,174.201111,0.144444,86316.08,35,84.888889,468.666667,2904514,...,1,0,7,0,0,0,39,3,0,0
27,starbucks coffee,buff0017,17.377778,376.552222,0.078889,93867.65,27,62.777778,322.555556,1748227,...,1,2,8,0,2,0,24,14,0,0
4,starbucks,buff0018,21.345000,207.323333,0.100000,108705.76,3,45.666667,285.222222,2686794,...,3,0,10,0,1,0,12,9,0,0
5,starbucks,buff0019,33.738333,353.212500,0.056250,117912.57,16,34.625000,227.500000,1284589,...,1,2,1,0,0,0,3,21,0,0
17,starbucks at samsung opera house,buff0020,40.529000,476.000000,0.131000,107649.99,33,25.000000,451.300000,3405417,...,2,0,6,0,0,0,35,4,0,0
28,starbucks coffee,buff0021,41.828750,501.535000,0.153750,93064.63,7,21.625000,403.125000,3275703,...,2,0,6,0,0,0,31,4,0,0
34,"starbucks coffee cunningham, india",buff0022,28.868571,65.433333,0.116667,142484.72,31,153.111111,382.222222,3459404,...,7,0,3,0,0,0,17,1,0,0
36,starbucks dollars colony,buff0023,23.140000,341.365000,0.133000,118562.69,45,30.500000,287.300000,1302210,...,2,0,2,0,0,0,7,12,0,0
14,starbucks - kalyananagar (s152),buff0024,29.337000,409.418000,0.087000,121135.02,23,54.300000,478.800000,4158149,...,2,0,0,0,2,0,1,21,0,0
29,starbucks coffee,buff0025,28.797143,90.460000,0.136667,153421.40,32,98.777778,351.777778,2641935,...,6,0,0,0,2,0,0,3,0,0
15,starbucks - prestige shantiniketan (s071),buff0026,18.220000,93.307273,0.080909,119547.27,10,64.727273,374.545455,5749688,...,3,3,0,0,2,0,23,31,0,0
30,starbucks coffee,buff0027,31.642500,374.648889,0.135556,113861.19,9,17.777778,278.333333,4949139,...,1,0,6,0,2,0,2,18,0,1
38,starbucks vega city,buff0028,25.365556,94.495556,0.101111,103598.39,4,69.222222,415.222222,5138829,...,1,0,11,0,2,0,9,13,0,0
31,starbucks coffee,buff0029,18.260000,314.836000,0.117000,139689.46,8,75.400000,293.300000,8047903,...,3,0,0,0,1,0,4,5,0,0
6,starbucks,buff0030,41.503333,200.277000,0.059000,133202.63,18,57.100000,394.100000,4556611,...,1,1,0,0,5,0,0,37,0,0
7,starbucks,buff0031,37.416667,66.190000,0.090000,131596.50,19,38.111111,166.333333,4336746,...,1,2,0,0,5,0,8,26,0,0
37,starbucks nexus shantiniketan,buff0032,18.388571,102.638000,0.096000,116802.98,10,70.400000,362.300000,6865900,...,3,3,0,0,5,0,21,28,0,0
8,starbucks,buff0033,27.566667,343.735000,0.114000,134412.72,13,35.300000,227.200000,3690480,...,0,3,2,0,2,0,11,39,0,1
32,starbucks coffee,buff0034,23.932500,149.615833,0.055000,149704.88,37,51.250000,376.833333,8695635,...,2,0,7,0,2,0,12,23,0,0
33,starbucks coffee,buff0035,16.346667,507.391000,0.074000,148657.82,10,78.500000,428.500000,8990008,...,2,5,17,0,1,0,16,3,0,0
16,starbucks - sjr central (s262),buff0036,17.377778,376.552222,0.078889,93867.65,27,62.777778,322.555556,1748227,...,1,2,8,0,2,0,24,14,0,0
40,starbucks vr mall,buff0037,23.105556,383.262727,0.103636,120732.81,53,83.545455,192.636364,3820777,...,1,4,3,0,3,0,5,6,0,0
18,starbucks bhartiya mall of bangalore,buff0038,133.915000,41.651429,0.142857,100314.18,23,33.857143,403.571429,4712787,...,0,1,3,0,4,0,1,11,0,0
9,starbucks,buff0039,50.595000,713.098571,0.142857,99136.35,4,36.428571,312.571429,3163216,...,1,0,1,0,1,0,1,2,0,0
11,starbucks - bhartiya city (s319),buff0040,100.883333,350.026250,0.127500,110886.81,23,31.625000,448.125000,4744863,...,0,1,3,0,4,0,1,11,0,0
10,starbucks,buff0041,40.955714,55.084286,0.141429,90005.11,5,49.714286,376.000000,2413856,...,1,0,3,0,1,0,20,3,0,0
13,starbucks - goldman sachs (s172),buff0042,41.503333,200.277000,0.059000,133202.63,18,57.100000,394.100000,4556611,...,1,1,0,0,5,0,0,37,0,0

In [102]:
df.to_csv(r"C:\Users\chemi\Desktop\enviroments\myml\1-Notebooks_python\All Scripts\extract datafrom the data base\output_csv\starbucks\all_data_on_buffer_level.csv")